# Generated by Django 5.2 on 2025-06-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_remove_productocarrito_carrito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='productopedido',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
